services:
  - type: web
    name: taskmaster-laravel
    env: docker
    branch: main  # Cambia si usas otra rama
    dockerfilePath: Dockerfile
    envVars:
      - key: APP_NAME
        value: Laravel
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:/9HtSwr0qrQQ/cJDNU4n967F1DF8mFiXvKSJ1pUv7tU=
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        value: https://taskmaster-tkm6.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d10gkgk9c44c73dmeq9g-a
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        value: postgres_taskmaster
      - key: DB_USERNAME
        value: postgres_taskmaster_user
      - key: DB_PASSWORD
        value: n8BqwUNE97ocT8D4v1jJEKdjPT7wVACg
      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_HOST
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: "587"
      - key: MAIL_USERNAME
        value: taskmaster962@gmail.com
      - key: MAIL_PASSWORD
        value: xgdassajfrvsbzex
      - key: MAIL_ENCRYPTION
        value: tls
      - key: MAIL_FROM_ADDRESS
        value: taskmaster962@gmail.com
      - key: MAIL_FROM_NAME
        value: "TaskMaster"
      - key: VITE_APP_NAME
        value: Laravel
      - key: VITE_APP_URL
        value: https://taskmaster-tkm6.onrender.com
